### ISSUE TITLE
Altered bass notes (e.g., '/D') not being transposed

### ISSUE THREAD

**Issue by Tembrel** [jsrmath/markato#25]
While Markato correctly plays chords with altered bass notes, it doesn't transpose them. The chord itself is transposed, but the bass is left alone.

The bug is in [this code](https://github.com/jsrmath/markato/blob/master/public/scripts/transpose.coffee#L8-L12), which replaces the chord note at the beginning of the chord string with the correct value, but doesn't change anything after that.

It looks like the [Sharp11 chord transpose method](https://github.com/jsrmath/sharp11/blob/master/lib/chord.js#L476-L480) would work here; it transposes both the chord and its bass.

**Comment by jsrmath** [comment]
Good catch.  I believe the reason I didn't just do that in the first place is that I thought it wouldn't properly handle weird/invalid chords, but apparently it does.  I should have trusted my own library.

**Comment by jsrmath** [comment]
Ohh.  Now I remember.  It's because Sharp11 chord objects don't preserve the original chord symbol you enter when dealing with aliases (for example, - would become m irreversibly).  There should be some way to get the chord with the original symbol in Sharp11.  I'll add that as an issue there.

**Comment by Tembrel** [comment]
Or just apply the same logic as in Sharp11:

```
    chord = s11.chord.create(chordStr)
    interval = s11.note.create(origKey).getInterval(newKey)
    newNote = chord.root.transpose(interval).clean()
    newBass = chord.bass.transpose(interval).clean()

    chordStr.replace(new RegExp('^' + chord.root), newNote)
    chordStr.replace(new RegExp('/' + chord.bass + '$'), newBass)
```

?

**Comment by Tembrel** [comment]
My suggested code was wrong; it strips the slash. I've added a comment to the last commit.

I don't have permission to re-open this issue, but that's what I'd do if I did.
