### ISSUE TITLE
Playback doesn't work for shared songs.

### ISSUE THREAD

**Issue by jsrmath** [jsrmath/markato#28]
I think I messed this up when I tried to lazily load the play function.

**Comment by Tembrel** [comment]
Should spacebar autoadvance? If so, then that's not working.

**Comment by jsrmath** [comment]
It should not.  The idea behind this UX is that you likely want to play a current chord multiple times before advancing to emulate strumming a guitar or playing a piano.

**Comment by jsrmath** [comment]
Fixed by cf5c3035a665840d66b178971a0d1d30c5783256

**Comment by Tembrel** [comment]
No way to guarantee that React renders first?

**Comment by jsrmath** [comment]
The issue before was that React wasn't aware of the play function, so it was a race condition.  I didn't notice, because React typically took longer to render than the play function took to load, however as I just discovered, that was not the case for shared songs.  Now that I've set the play function as part of the component's state, it doesn't matter if the component loads first, because it will update automatically when the state changes.
